version: '3.7'

services:
  frontend:
    build: ./frontend
    container_name: react_frontend
    labels:
      - 'traefik.http.routers.frontend.rule=Host(`damtrix.mooo.com`)'
      - 'traefik.http.services.frontend.loadbalancer.server.port=80'

  backend:
    build: ./backend
    container_name: fastapi_backend
    labels:
      - 'traefik.http.routers.backend.rule=Host(`damtrix.mooo.com`) && (PathPrefix(`/api`) || PathPrefix(`/docs`) || PathPrefix(`/redoc`))'
      - 'traefik.http.services.backend.loadbalancer.server.port=8000'

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: damtrix
      POSTGRES_PASSWORD: justpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: adminer
    labels:
      - 'traefik.http.routers.adminer.rule=Host(`db.damtrix.mooo.com`)'
    ports:
      - '8080:8080'

  traefik:
    image: traefik:v2.2
    container_name: traefik
    command:
      - '--api.insecure=true'
      - '--providers.docker=true'
      - '--entrypoints.web.address=:80'
      - '--entrypoints.websecure.address=:443'
      - '--certificatesresolvers.myresolver.acme.tlschallenge=true'
      - '--certificatesresolvers.myresolver.acme.email=your-email@example.com'
      - '--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json'
      - '--entrypoints.web.http.redirections.entrypoint.to=websecure'
      - '--entrypoints.web.http.redirections.entrypoint.scheme=https'
    ports:
      - '80:80'
      - '8090:8090'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - './letsencrypt:/letsencrypt'
    labels:
      - 'traefik.http.routers.api.rule=Host(`proxy.damtrix.mooo.com`)'
      - 'traefik.http.services.api.loadbalancer.server.port=8090'

volumes:
  postgres_data:
