version: '3.8'

services:
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - '5137:5137'
    env_file: './frontend/.env'

  backend:
    env_file: './backend/.env'
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - '8000:8000'
    # environment:
    #   - DOMAIN=18.212.207.22/
    #   - ENVIRONMENT=local
    #   - PROJECT_NAME=Full Stack FastAPI Project
    #   - STACK_NAME=full-stack-fastapi-project
    #   - BACKEND_CORS_ORIGINS=http://localhost,http://localhost:5173,https://localhost,https://localhost:5173,http://damtrix.mooo.com,https://damtrix.mooo.com
    #   - SECRET_KEY=changethis123
    #   - FIRST_SUPERUSER=devops@hng.tech
    #   - FIRST_SUPERUSER_PASSWORD=devops#HNG11
    #   - USERS_OPEN_REGISTRATION=True
    #   - SMTP_HOST=
    #   - SMTP_USER=
    #   - SMTP_PASSWORD=
    #   - EMAILS_FROM_EMAIL=info@example.com
    #   - SMTP_TLS=True
    #   - SMTP_SSL=False
    #   - SMTP_PORT=587
    #   - POSTGRES_SERVER=db
    #   - POSTGRES_DB=hngstage2
    #   - POSTGRES_USER=damtrix
    #   - POSTGRES_PASSWORD=helpmeohlord
    # depends_on:
    #   - db

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: hng11devops
      POSTGRES_USER: damtrix
      POSTGRES_PASSWORD: helpmeohlord

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - '8080:8080'

  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:latest
    restart: unless-stopped
    container_name: nginx-proxy-manager
    ports:
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '8090:81' # Admin Web Port

    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt

networks:
  web:
    driver: bridge
