version: '3.8'

services:
  frontend:
    build: ./frontend
    container_name: frontend
    networks:
      - web

  backend:
    build: ./backend
    container_name: backend
    networks:
      - web
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app_db
    networks:
      - web

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - '8080:8080'
    networks:
      - web

  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy-manager
    ports:
      - '8090:80'
      - '81:81'
      - '443:443'
    networks:
      - web
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt

networks:
  web:
    driver: bridge
